# <span style="color:red; font-size:25px"> DATASCI 151 - Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

<!-- - This is a graded quiz. Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED. </span> -->

- AI assistance is <span style="color:red"> NOT </span> permitted for this assignment.

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [1]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "4">

Import any packages you would like in the cell below. Or, import them as needed later in the notebook.

In [2]:
# import packages

import pandas as pd
import numpy as np

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories. (**Both** endpoints are included in the listed categories)

    - **Silent Era**: Films made between 1917 and 1927

    - **Golden Age**: Films made between 1928 and 1949

    - **Post-War**: Films made between 1950 and 1964

    - **New Hollywood**: Films made between 1965 and 1974

    - **Blockbuster Era**: Movies made between 1975 and 2000

    - **Digital Age**: Movies made between 2001 until the present

- You must use the `pd.cut` function to recode this variable.

- Add a new column to the DataFrame called "Era" that contains this recoded variable.

In [3]:
# your code here

df = pd.read_csv("quiz_data/movies.csv")

year_bins = [1916, 1927, 1949, 1964,1974,2000, np.inf]
year_labels = ["Slient Era", "Golden Age", "Post-War","New Hollywood","Blockbuster Era","Digital Age"]


df["time_period"] = pd.cut(x = df["Year"], 
                bins=year_bins, 
                labels = year_labels)

display(df.sort_values(by = "Year"))

,Title,IMDb rating,Year,MPA rating,Genre,Director,Star Cast,MetaScore,Duration (minutes),time_period
3835,She,6.9,1917,R,Drama,Kenean Buel,Valeska SurattBen TaggartMiriam Fouche,66.0,116.3,Slient Era
1090,"Homunculus, 6. Teil - Das Ende des Homunculus",6.7,1917,R,Drama,Otto Rippert,Olaf FønssFriedrich KühneMechthildis Thein,66.0,116.3,Slient Era
1456,A léleklátó sugár,5.3,1918,R,Sci-Fi,Alfréd Deésy,Daniel RadcliffeEmma WatsonRupert Grint,66.0,116.3,Slient Era
67,The Kid,8.2,1921,Other,Comedy,Charles Chaplin,Charles Chaplin,57.1,68.0,Slient Era
2067,The City Struck by Lightning,5.7,1924,R,Sci-Fi,Luitz-Morat,Daniel MendailleJane MaguenatArmand Morins,66.0,116.3,Slient Era
...,...,...,...,...,...,...,...,...,...,...
342,Harold and the Purple Crayon,7.1,2024,PG,Animation,Carlos Saldanha,Zachary LeviLil Rel HoweryBenjamin Bottani,66.9,92.0,Digital Age
3110,Orion and the Dark,6.3,2024,Other,Animation,Sean Charmatz,Jacob Tremblay,72.0,93.0,Digital Age
1491,Under Paris,6.9,2024,R,Action,Xavier Gens,Sebastien AuscherYannick DahanXavier Gens,66.0,116.3,Digital Age
1247,Minecraft,7.1,2025,R,Action,Jared Hess,Chris BowmanHubbel PalmerAllison Schroeder,66.9,116.3,Digital Age
2115,Blade,6.9,2025,R,Action,Yann Demange,Gene ColanMichael GreenStacy Osei-Kuffour,66.0,116.3,Digital Age

<font size = "4">

**Q2** Conditional Subsetting

<font size = "3">

- Continue to use the movies DataFrame from Q1 (or read it in again)

- Return a DataFrame with the **6 shortest movies** that (a) were released 2011 or later, and (b) have IMDb rating of 6.0 or greater.

**Hint**: The column containing the IMDb rating is named "IMDb rating", which would not be a valid Python variable because of the space. If this causes you trouble and you don't remember how to handle it, you could simply rename the column to "IMDb_rating".

In [4]:
# your code here


df = df.rename(columns={"IMDb rating": "IMDb_rating"})

df.query("Year >= 2011 and IMDb_rating >=6.0").sort_values(by="Duration (minutes)",ascending=True).head(6)

,Title,IMDb_rating,Year,MPA rating,Genre,Director,Star Cast,MetaScore,Duration (minutes),time_period
784,Words of Everest,7.4,2013,PG,Documentary,Paul Copeland,Stephen Campbell MooreJon Edgley-BondJason Fle...,66.0,46.0,Digital Age
3857,TED Rising,6.6,2016,PG-13,Action,Bartu Atabek,Onat YigitMert SayarNevzat Özdemir,66.0,50.0,Digital Age
621,Projections of America,8.0,2014,PG,Documentary,Peter Miller,John LithgowVictoria RiskinIan Scott,66.0,52.0,Digital Age
1739,Hawaii the Stolen Paradise,6.3,2014,PG-13,Documentary,Luis Castro,Daniel RadcliffeEmma WatsonRupert Grint,66.0,53.0,Digital Age
280,9/11 Inside the Pentagon,7.0,2016,PG,Documentary,Sharon Petzold,Daniel RadcliffeEmma WatsonRupert Grint,66.0,54.0,Digital Age
1657,Voices from Within,6.4,2014,PG-13,Documentary,Joy Haynes,Lewis EckerKevin McCainJames Snyder,66.0,54.0,Digital Age

<font size = "4">

**Q3** Aggregating Group Statistics with Chaining

<font size = "3">

- Continue to use the movies DataFrame from Q1 (or read it in again)

- The column "MPA rating" shows whether the movie was rated R, PG-13, etc. Aggregate the following statistics for each MPA rating:

    - Mean IMDb rating

    - Median duration (in minutes)

- Sort the resulting DataFrame by mean IMDb rating in **ascending** order.

- For full credit, execute all commands on a single line by chaining

In [5]:
# your code here

(df.groupby("MPA rating").agg(avg_imdb = ('IMDb_rating', 'mean'),
                     med_duration= ('Duration (minutes)', 'median')).
                     sort_values(by = "avg_imdb", ascending = True))

            avg_imdb  med_duration
MPA rating
X           6.100000          90.0
NC-17       6.544444         105.0
PG          6.613674         100.0
Other       6.671545          98.0
Not Rated   6.696748          93.0
R           6.795246         116.3
PG-13       6.956572         116.0
G           6.999614          93.0

<font size = "4">

**Q4** Calculate laps per minute

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Create a new column called "laps_per_minute" which is calculated by the formula: $\ \dfrac{\textrm{laps}}{\textrm{race\_duration\_minutes}}$

- Group the data by **both** "raceId" and "driverId" and calculate the **maximum laps per minutes** for each group.

- Sort the data in descending order and then extract the raceId/driverId pairs with the 5 highest laps per minute

<br>

**Hint**: For a Pandas Series, the `.sort_values()` method does **not** take the keyword "by".

In [6]:
# your code here

df_results = pd.read_csv("quiz_data/results_cleaned.csv")

df_results["race_duration_minutes"] = df_results["milliseconds"] / 6e4

df_results["laps_per_minute"]=df_results["laps"]/df_results["race_duration_minutes"]

gb = df_results.groupby(["raceId", "constructorId"])

gb["laps_per_minute"].max().sort_values(ascending=False).head(5)

raceId  constructorId
653     6                1.106920
        37               1.093937
598     32               0.976598
        6                0.972569
        25               0.971045
Name: laps_per_minute, dtype: float64

<font size = "4">

**Q5** Aggregate and query

<font size = "3">

- Continue to use the "results_cleaned.csv" DataFrame from Q4 (or read it in again)

- Do the following in a single line using chaining:

    - Extract the subset with raceId equal to 21.

    - Aggregate the minimum number of points and average number of points for each constructor in the subset.

    - Extract the subset of these constructors with average number of points **strictly greater than 1**

In [7]:
# your code here


df1 = pd.read_csv("quiz_data/results_cleaned.csv")

(df1.query("raceId == 21").
 groupby("constructorId").
 agg(min_points = ('points', 'min'), avg_points = ('points', 'mean')).
 query("avg_points > 1"))

               min_points  avg_points
constructorId
1                     0.0         3.0
2                     0.0         2.5
6                     8.0         9.0
9                     0.0         2.0
11                    0.0         1.5

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv" (or read it in again).

- We might consider it a "bad day" for an F1 driver if they finish outside the top ten (11th or worse). Write a function that takes in a Pandas Series and returns the number of entries $ > 10$.

- Group by "driverId" and then aggregate the following statistics based on the "positionOrder" column: the average (mean) position and the number of finishes outside the top ten.

- Use your custom function for this second statistic.

- Merge the aggregated data back **into the original DataFrame**.

In [10]:
# your code here

df2= pd.read_csv("quiz_data/results_cleaned.csv")

def check(col):
    return (col > 10).sum()

df_agg = df_results.groupby(by="driverId").agg(avg_points = ("positionOrder", "mean"),
                                      number_finishes_outside_top10 = ("positionOrder", check))

df_final = pd.merge(left = df2, right = df_agg, on = "driverId", how = "left")

print(df_final.head())

   resultId  raceId  driverId  constructorId number  grid position  \
0         1      18         1              1     22     1        1
1         2      18         2              2      3     5        2
2         3      18         3              3      7     7        3
3         4      18         4              4      5    11        4
4         5      18         5              1     23     3        5

  positionText  positionOrder  points  laps         time  milliseconds  \
0            1              1    10.0    58  1:34:50.616     5690616.0
1            2              2     8.0    58       +5.478     5696094.0
2            3              3     6.0    58       +8.163     5698779.0
3            4              4     5.0    58      +17.181     5707797.0
4            5              5     4.0    58      +18.014     5708630.0

  fastestLap rank fastestLapTime fastestLapSpeed  statusId  avg_points  \
0         39    2       1:27.452         218.300         1    4.707641
1         41    3       1:27.739         217.586         1   10.722826
2         41    5       1:28.090         216.719         1    8.252427
3         58    7       1:28.603         215.464         1    8.409742
4         43    1       1:27.418         218.385         1   13.285714

   number_finishes_outside_top10
0                             37
1                             83
2                             62
3                            116
4                             76